"""baseline: adopt existing schema

Revision ID: 67c4a50e3f19
Revises: 
Create Date: 2026-07-05 19:38:32.522483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c4a50e3f19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=120), nullable=False),
    sa.Column('public_identifier', sa.String(length=160), nullable=True),
    sa.Column('provider_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('last_headline', sa.Text(), nullable=False),
    sa.Column('headline_changed_at', sa.DateTime(), nullable=True),
    sa.Column('last_post_id', sa.String(length=160), nullable=True),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('posts_checked_at', sa.DateTime(), nullable=True),
    sa.Column('post_checks', sa.Integer(), nullable=False),
    sa.Column('empty_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_persons_member_id'), 'monitored_persons', ['member_id'], unique=True)
    op.create_index(op.f('ix_monitored_persons_posts_checked_at'), 'monitored_persons', ['posts_checked_at'], unique=False)
    op.create_index(op.f('ix_monitored_persons_public_identifier'), 'monitored_persons', ['public_identifier'], unique=False)
    op.create_table('stripe_webhook_events',
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('tenant_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('wrapped_dek', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_keys_tenant_id'), 'tenant_keys', ['tenant_id'], unique=True)
    op.create_table('triage_enrichment_cache',
    sa.Column('cache_key', sa.String(length=80), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unipile_account_id', sa.String(length=80), nullable=True),
    sa.Column('google_sub', sa.String(length=80), nullable=True),
    sa.Column('microsoft_sub', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verify_code_hash', sa.String(length=200), nullable=True),
    sa.Column('email_verify_code_expires', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=400), nullable=True),
    sa.Column('linkedin_public_id', sa.String(length=120), nullable=True),
    sa.Column('linkedin_provider_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('linkedin_status', sa.String(length=20), nullable=False),
    sa.Column('linkedin_chat_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('autonomy_mode', sa.String(length=8), nullable=False),
    sa.Column('unipile_email_account_id', sa.String(length=80), nullable=True),
    sa.Column('email_account_address', sa.String(length=200), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('email_connected_at', sa.DateTime(), nullable=True),
    sa.Column('unipile_whatsapp_account_id', sa.String(length=80), nullable=True),
    sa.Column('whatsapp_status', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_connected_at', sa.DateTime(), nullable=True),
    sa.Column('voice_examples', sa.Text(), nullable=False),
    sa.Column('voice_synced_at', sa.DateTime(), nullable=True),
    sa.Column('voice_profile', sa.Text(), nullable=False),
    sa.Column('auto_followups_enabled', sa.Boolean(), nullable=False),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('saved_send_link', sa.String(length=400), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=30), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=120), nullable=True),
    sa.Column('drafts_used_this_period', sa.Integer(), nullable=False),
    sa.Column('contacts_scanned_this_period', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    op.create_index(op.f('ix_users_microsoft_sub'), 'users', ['microsoft_sub'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_users_unipile_account_id'), 'users', ['unipile_account_id'], unique=True)
    op.create_index(op.f('ix_users_unipile_email_account_id'), 'users', ['unipile_email_account_id'], unique=True)
    op.create_index(op.f('ix_users_unipile_whatsapp_account_id'), 'users', ['unipile_whatsapp_account_id'], unique=True)
    op.create_table('auth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_states_state_token'), 'auth_states', ['state_token'], unique=True)
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account_email', sa.String(length=200), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'account_email', name='uq_connected_account')
    )
    op.create_index(op.f('ix_connected_accounts_provider'), 'connected_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_connected_accounts_status'), 'connected_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_identity_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('linkedin_public_id', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('company_domain', sa.String(length=160), nullable=True),
    sa.Column('email_thread_id', sa.String(length=160), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('seen_post_ids', sa.Text(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('profile_baselined_at', sa.DateTime(), nullable=True),
    sa.Column('watch_error', sa.String(length=300), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'primary_identity_key', name='uq_contact_owner_identity')
    )
    op.create_index(op.f('ix_contacts_primary_identity_key'), 'contacts', ['primary_identity_key'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('unipile_account_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_unipile_account_id'), 'email_accounts', ['unipile_account_id'], unique=True)
    op.create_index(op.f('ix_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False)
    op.create_table('email_pending_outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('first_out_at', sa.DateTime(), nullable=True),
    sa.Column('last_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address', name='uq_pending_outreach_user_addr')
    )
    op.create_index(op.f('ix_email_pending_outreach_address'), 'email_pending_outreach', ['address'], unique=False)
    op.create_index(op.f('ix_email_pending_outreach_user_id'), 'email_pending_outreach', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('seniority', sa.String(length=200), nullable=False),
    sa.Column('co_stage', sa.String(length=120), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=False),
    sa.Column('event_name', sa.String(length=160), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('goal', sa.String(length=300), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('sources', sa.String(length=120), nullable=False),
    sa.Column('yoe', sa.String(length=80), nullable=False),
    sa.Column('triage_config', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=400), nullable=True),
    sa.Column('linkedin_url', sa.String(length=400), nullable=True),
    sa.Column('raw_application_data', sa.Text(), nullable=False),
    sa.Column('enrichment_data', sa.Text(), nullable=False),
    sa.Column('enrichment_raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=False)
    op.create_index(op.f('ix_applicants_event_id'), 'applicants', ['event_id'], unique=False)
    op.create_table('contact_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'key', 'dedup_key', name='uq_contact_fact')
    )
    op.create_index(op.f('ix_contact_facts_contact_id'), 'contact_facts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_facts_due_date'), 'contact_facts', ['due_date'], unique=False)
    op.create_index(op.f('ix_contact_facts_key'), 'contact_facts', ['key'], unique=False)
    op.create_index(op.f('ix_contact_facts_user_id'), 'contact_facts', ['user_id'], unique=False)
    op.create_table('contact_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'value', name='uq_contact_identity_value')
    )
    op.create_index(op.f('ix_contact_identities_contact_id'), 'contact_identities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_identities_kind'), 'contact_identities', ['kind'], unique=False)
    op.create_index(op.f('ix_contact_identities_user_id'), 'contact_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_contact_identities_value'), 'contact_identities', ['value'], unique=False)
    op.create_table('curation_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('linkedin_url', sa.String(length=400), nullable=True),
    sa.Column('list_source', sa.String(length=40), nullable=False),
    sa.Column('rsvp_status', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('enrichment', sa.Text(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('news_signal', sa.Text(), nullable=False),
    sa.Column('recognition_flags', sa.Text(), nullable=False),
    sa.Column('warm_connection', sa.Text(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('fit_rule_trace', sa.Text(), nullable=False),
    sa.Column('fit_rationale', sa.Text(), nullable=False),
    sa.Column('no_show_probability', sa.Float(), nullable=True),
    sa.Column('no_show_rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_attendees_email'), 'curation_attendees', ['email'], unique=False)
    op.create_index(op.f('ix_curation_attendees_event_id'), 'curation_attendees', ['event_id'], unique=False)
    op.create_table('host_person_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=120), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_in_relations_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_user_id', 'member_id', name='uq_host_person')
    )
    op.create_index(op.f('ix_host_person_links_contact_id'), 'host_person_links', ['contact_id'], unique=False)
    op.create_index(op.f('ix_host_person_links_host_user_id'), 'host_person_links', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_host_person_links_member_id'), 'host_person_links', ['member_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('runner', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_event_id'), 'jobs', ['event_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('outgoing_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_handle', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outgoing_messages_contact_id'), 'outgoing_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outgoing_messages_scheduled_at'), 'outgoing_messages', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_outgoing_messages_status'), 'outgoing_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outgoing_messages_user_id'), 'outgoing_messages', ['user_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('seniority', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('works_on', sa.String(length=60), nullable=False),
    sa.Column('offers', sa.String(length=200), nullable=False),
    sa.Column('seeks', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('recent_activity', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('gh_stars', sa.Integer(), nullable=False),
    sa.Column('x_followers', sa.Integer(), nullable=False),
    sa.Column('scholar_citations', sa.Integer(), nullable=False),
    sa.Column('li_resolved', sa.Boolean(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('linkedin_provider_id', sa.String(length=120), nullable=True),
    sa.Column('sources', sa.String(length=80), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('fit_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('private_note', sa.String(length=500), nullable=True),
    sa.Column('contact_type', sa.String(length=20), nullable=True),
    sa.Column('next_step', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('connection_checked_at', sa.DateTime(), nullable=True),
    sa.Column('draft_status', sa.String(length=12), nullable=True),
    sa.Column('draft_note', sa.String(length=400), nullable=True),
    sa.Column('draft_message', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_contact_id'), 'prospects', ['contact_id'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('buyer_profile', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_event_id'), 'sponsors', ['event_id'], unique=False)
    op.create_table('applicant_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('archetype', sa.String(length=40), nullable=False),
    sa.Column('sponsor_fit', sa.Integer(), nullable=False),
    sa.Column('event_fit', sa.Integer(), nullable=False),
    sa.Column('role_relevance', sa.Integer(), nullable=False),
    sa.Column('company_relevance', sa.Integer(), nullable=False),
    sa.Column('stage_relevance', sa.Integer(), nullable=False),
    sa.Column('seriousness_legitimacy', sa.Integer(), nullable=False),
    sa.Column('room_value', sa.Integer(), nullable=False),
    sa.Column('application_quality', sa.Integer(), nullable=False),
    sa.Column('one_sentence_summary', sa.Text(), nullable=False),
    sa.Column('why_fit', sa.Text(), nullable=False),
    sa.Column('why_not_fit', sa.Text(), nullable=False),
    sa.Column('evidence_used', sa.Text(), nullable=False),
    sa.Column('missing_info', sa.Text(), nullable=False),
    sa.Column('suggested_review_action', sa.Text(), nullable=False),
    sa.Column('verifier_ran', sa.Boolean(), nullable=False),
    sa.Column('verifier_adjustments', sa.Text(), nullable=False),
    sa.Column('verifier_reason', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_evaluations_applicant_id'), 'applicant_evaluations', ['applicant_id'], unique=True)
    op.create_index(op.f('ix_applicant_evaluations_event_id'), 'applicant_evaluations', ['event_id'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=60), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curation_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['curation_attendees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_attributions_attendee_id'), 'curation_attributions', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_curation_attributions_event_id'), 'curation_attributions', ['event_id'], unique=False)
    op.create_table('curation_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['curation_attendees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_followups_attendee_id'), 'curation_followups', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_curation_followups_event_id'), 'curation_followups', ['event_id'], unique=False)
    op.create_table('curation_intros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('from_attendee_id', sa.Integer(), nullable=False),
    sa.Column('to_attendee_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rule_trace', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['from_attendee_id'], ['curation_attendees.id'], ),
    sa.ForeignKeyConstraint(['to_attendee_id'], ['curation_attendees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_intros_event_id'), 'curation_intros', ['event_id'], unique=False)
    op.create_table('curation_llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['curation_attendees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_llm_calls_attendee_id'), 'curation_llm_calls', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_curation_llm_calls_event_id'), 'curation_llm_calls', ['event_id'], unique=False)
    op.create_index(op.f('ix_curation_llm_calls_purpose'), 'curation_llm_calls', ['purpose'], unique=False)
    op.create_table('match_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['a_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['b_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_lead_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('inbound_body', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_replies_prospect_id'), 'pending_replies', ['prospect_id'], unique=False)
    op.create_table('relationship_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('company_domain', sa.String(length=160), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('interaction_type', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_interactions_actor_user_id'), 'relationship_interactions', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_relationship_interactions_contact_id'), 'relationship_interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_relationship_interactions_event_id'), 'relationship_interactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_relationship_interactions_occurred_at'), 'relationship_interactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_relationship_interactions_prospect_id'), 'relationship_interactions', ['prospect_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('system_recommendation', sa.String(length=20), nullable=False),
    sa.Column('human_decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_applicant_id'), 'review_decisions', ['applicant_id'], unique=True)
    op.create_index(op.f('ix_review_decisions_event_id'), 'review_decisions', ['event_id'], unique=False)
    op.create_table('scheduled_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('suggested_send_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_reason', sa.String(length=20), nullable=False),
    sa.Column('booking_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_followups_prospect_id'), 'scheduled_followups', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_scheduled_followups_send_at'), 'scheduled_followups', ['send_at'], unique=False)
    op.create_index(op.f('ix_scheduled_followups_status'), 'scheduled_followups', ['status'], unique=False)
    op.create_table('sponsor_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_matches_prospect_id'), 'sponsor_matches', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_sponsor_matches_sponsor_id'), 'sponsor_matches', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsor_matches_sponsor_id'), table_name='sponsor_matches')
    op.drop_index(op.f('ix_sponsor_matches_prospect_id'), table_name='sponsor_matches')
    op.drop_table('sponsor_matches')
    op.drop_index(op.f('ix_scheduled_followups_status'), table_name='scheduled_followups')
    op.drop_index(op.f('ix_scheduled_followups_send_at'), table_name='scheduled_followups')
    op.drop_index(op.f('ix_scheduled_followups_prospect_id'), table_name='scheduled_followups')
    op.drop_table('scheduled_followups')
    op.drop_index(op.f('ix_review_decisions_event_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_applicant_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_relationship_interactions_prospect_id'), table_name='relationship_interactions')
    op.drop_index(op.f('ix_relationship_interactions_occurred_at'), table_name='relationship_interactions')
    op.drop_index(op.f('ix_relationship_interactions_event_id'), table_name='relationship_interactions')
    op.drop_index(op.f('ix_relationship_interactions_contact_id'), table_name='relationship_interactions')
    op.drop_index(op.f('ix_relationship_interactions_actor_user_id'), table_name='relationship_interactions')
    op.drop_table('relationship_interactions')
    op.drop_index(op.f('ix_pending_replies_prospect_id'), table_name='pending_replies')
    op.drop_table('pending_replies')
    op.drop_table('outreach_log')
    op.drop_table('match_edges')
    op.drop_index(op.f('ix_curation_llm_calls_purpose'), table_name='curation_llm_calls')
    op.drop_index(op.f('ix_curation_llm_calls_event_id'), table_name='curation_llm_calls')
    op.drop_index(op.f('ix_curation_llm_calls_attendee_id'), table_name='curation_llm_calls')
    op.drop_table('curation_llm_calls')
    op.drop_index(op.f('ix_curation_intros_event_id'), table_name='curation_intros')
    op.drop_table('curation_intros')
    op.drop_index(op.f('ix_curation_followups_event_id'), table_name='curation_followups')
    op.drop_index(op.f('ix_curation_followups_attendee_id'), table_name='curation_followups')
    op.drop_table('curation_followups')
    op.drop_index(op.f('ix_curation_attributions_event_id'), table_name='curation_attributions')
    op.drop_index(op.f('ix_curation_attributions_attendee_id'), table_name='curation_attributions')
    op.drop_table('curation_attributions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_applicant_evaluations_event_id'), table_name='applicant_evaluations')
    op.drop_index(op.f('ix_applicant_evaluations_applicant_id'), table_name='applicant_evaluations')
    op.drop_table('applicant_evaluations')
    op.drop_index(op.f('ix_sponsors_event_id'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_contact_id'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_outgoing_messages_user_id'), table_name='outgoing_messages')
    op.drop_index(op.f('ix_outgoing_messages_status'), table_name='outgoing_messages')
    op.drop_index(op.f('ix_outgoing_messages_scheduled_at'), table_name='outgoing_messages')
    op.drop_index(op.f('ix_outgoing_messages_contact_id'), table_name='outgoing_messages')
    op.drop_table('outgoing_messages')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_event_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_host_person_links_member_id'), table_name='host_person_links')
    op.drop_index(op.f('ix_host_person_links_host_user_id'), table_name='host_person_links')
    op.drop_index(op.f('ix_host_person_links_contact_id'), table_name='host_person_links')
    op.drop_table('host_person_links')
    op.drop_index(op.f('ix_curation_attendees_event_id'), table_name='curation_attendees')
    op.drop_index(op.f('ix_curation_attendees_email'), table_name='curation_attendees')
    op.drop_table('curation_attendees')
    op.drop_index(op.f('ix_contact_identities_value'), table_name='contact_identities')
    op.drop_index(op.f('ix_contact_identities_user_id'), table_name='contact_identities')
    op.drop_index(op.f('ix_contact_identities_kind'), table_name='contact_identities')
    op.drop_index(op.f('ix_contact_identities_contact_id'), table_name='contact_identities')
    op.drop_table('contact_identities')
    op.drop_index(op.f('ix_contact_facts_user_id'), table_name='contact_facts')
    op.drop_index(op.f('ix_contact_facts_key'), table_name='contact_facts')
    op.drop_index(op.f('ix_contact_facts_due_date'), table_name='contact_facts')
    op.drop_index(op.f('ix_contact_facts_contact_id'), table_name='contact_facts')
    op.drop_table('contact_facts')
    op.drop_index(op.f('ix_applicants_event_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_email_pending_outreach_user_id'), table_name='email_pending_outreach')
    op.drop_index(op.f('ix_email_pending_outreach_address'), table_name='email_pending_outreach')
    op.drop_table('email_pending_outreach')
    op.drop_index(op.f('ix_email_accounts_user_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_unipile_account_id'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_primary_identity_key'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_status'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_provider'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_auth_states_state_token'), table_name='auth_states')
    op.drop_table('auth_states')
    op.drop_index(op.f('ix_users_unipile_whatsapp_account_id'), table_name='users')
    op.drop_index(op.f('ix_users_unipile_email_account_id'), table_name='users')
    op.drop_index(op.f('ix_users_unipile_account_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_microsoft_sub'), table_name='users')
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('triage_enrichment_cache')
    op.drop_index(op.f('ix_tenant_keys_tenant_id'), table_name='tenant_keys')
    op.drop_table('tenant_keys')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('ix_monitored_persons_public_identifier'), table_name='monitored_persons')
    op.drop_index(op.f('ix_monitored_persons_posts_checked_at'), table_name='monitored_persons')
    op.drop_index(op.f('ix_monitored_persons_member_id'), table_name='monitored_persons')
    op.drop_table('monitored_persons')
    # ### end Alembic commands ###
